import { Rubik } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/Navbar';
import Footer from '@/component/footer/Footer';

const inter = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='aside-img'>
          <img src='./assets/Frame 812073.png' alt=''/>
          <img src='./assets/Group 2207.png' alt=''/>
        </div>
        {/* Navbar Section */}
        <Navbar />
        {/* Navbar Section */}
        {children}
         {/* Footer Section */}
         <Footer />
        {/* Footer Section */}
      </body>
    </html>
  )
}
